#!/bin/bash
RAILS=$HOME/git/rails
TEST=$HOME/tmp

function runtest {
  echo -e "\n$1"
  cd $RAILS
  git checkout $1
  git log -3 --pretty=one | cat
  cd $TEST 
  rm -rf depot
  ruby $RAILS/railties/bin/rails depot
  cd depot
  ln -s $RAILS vendor/rails
  ruby script/generate scaffold product
  if [ -e app/models/product.rb ]; then
    log[${#log[*]}]="$1 pass"
  else
    log[${#log[*]}]="$1 fail"
  fi
}

runtest origin/master
runtest origin/2-2-stable
runtest origin/2-3-stable
runtest 16f36b6171c855dcc92ef557c454fcfc314b617f
runtest 2d9b45722c5639ad822f9a213edfd4d2bb084dcb

echo -e "\nSummary:"
for (( i=0; i<${#log[*]}; i++ )) do
  printf "  %-40s %s\n" ${log[$i]}
done
